# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'bing-ads-api'
require 'helpers/bing_ads_factory'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.after(:all) do
    # Clean up everything
    account_id = "8506945"
    service = BingAdsApi::CampaignManagement.new(
      environment: :sandbox,
      username: "ruby_bing_ads_sbx",
      password: "sandbox123",
      developer_token: "BBD37VB98",
      customer_id: "21025739",
      account_id: account_id
    )
    campaign_ids = service.get_campaigns_by_account_id(account_id).map do |c|
      p c
      c.id
    end

    campaign_ids.each_slice(100) do |ids|
      service.delete_campaigns(account_id, ids)
    end
  end
end
